export const checklist = [
  {
    id: 1,
    cat: "Content",
    task: "Content Analysis",
    link: "https://smallseotools.ai/online-word-counter/",
    method: "auto-check",
    checkKey: "contentAnalysis",
    desc: "Word count, uniqueness ratio, aur readability check.",
  },
  {
    id: 2,
    cat: "Content",
    task: "Readability Score",
    method: "auto-check",
    checkKey: "readability",
    link: "https://readabilityformulas.com/flesch-reading-ease-readability-formula.php",
    desc: "Flesch score se content readability check karein.",
  },
  {
    id: 12,
    cat: "Social",
    task: "Open Graph Tags",
    method: "auto-check",
    checkKey: "openGraph",
    link: "https://developers.facebook.com/tools/debug/",
    desc: "WhatsApp/Facebook share pe kaise dikhega.",
  },
  {
    id: 3,
    cat: "On-Page",
    task: "Keyword Density",
    link: "https://smallseotools.ai/keywords-ai-tool/",
    method: "auto-check",
    checkKey: "keywordDensity",
    desc: "Top keywords aur unki density check karein.",
  },
  {
    id: 4,
    cat: "On-Page",
    task: "Meta Tags Check",
    link: "https://smallseotools.ai/seo-meta-description-generating-ai-tool/",
    method: "auto-check",
    checkKey: "metaTags",
  },
  {
    id: 5,
    cat: "Authority",
    task: "Link Profile",
    link: "https://ahrefs.com/backlink-checker",
    method: "auto-check",
    checkKey: "linkProfile",
    desc: "Internal/External links aur domains analysis.",
  },
  {
    id: 6,
    cat: "Authority",
    task: "Outbound Links",
    link: "https://ahrefs.com/backlink-checker",
    method: "auto-check",
    checkKey: "linkProfile",
    desc: "External links aur referring domains dekhein.",
  },
  {
    id: 7,
    cat: "Authority",
    task: "Security Headers",
    link: "https://securityheaders.com/",
    method: "auto-check",
    checkKey: "securityCheck",
    desc: "HTTPS, HSTS, CSP, X-Frame headers check.",
  },
  {
    id: 8,
    cat: "Technical",
    task: "Sitemap Generator",
    link: "https://www.xml-sitemaps.com/",
    method: "auto-check",
    checkKey: "sitemap",
  },
  {
    id: 9,
    cat: "Technical",
    task: "Robots.txt Gen",
    link: "https://en.ryte.com/free-tools/robots-txt/",
    method: "auto-check",
    checkKey: "robots",
  },
  {
    id: 10,
    cat: "Technical",
    task: "Website Speed",
    link: "https://pagespeed.web.dev/",
    method: "auto-score",
    scoreKey: "performance",
  },
  {
    id: 11,
    cat: "Images",
    task: "Image Compression",
    link: "https://tinypng.com/",
    method: "auto-check",
    checkKey: "images",
  },
  {
    id: 13,
    cat: "Security",
    task: "SSL Certificate",
    method: "auto-check",
    checkKey: "sslCertificate",
    link: "https://www.ssllabs.com/ssltest/",
    desc: "SSL certificate expiry aur issuer check.",
  },
  {
    id: 14,
    cat: "Technical",
    task: "Structured Data",
    method: "auto-check",
    checkKey: "structuredData",
    link: "https://validator.schema.org/",
    desc: "Schema.org / JSON-LD markup check.",
  },
  {
    id: 15,
    cat: "Mobile",
    task: "Mobile-Friendly",
    method: "auto-check",
    checkKey: "mobileFriendly",
    link: "https://search.google.com/test/mobile-friendly",
    desc: "Viewport, responsive CSS, font sizes check.",
  },
  {
    id: 16,
    cat: "On-Page",
    task: "Canonical URL",
    method: "auto-check",
    checkKey: "canonicalUrl",
    link: "https://www.seoreviewtools.com/canonical-url-checker/",
    desc: "Canonical tag validation.",
  },
  {
    id: 17,
    cat: "Technical",
    task: "Page Structure",
    method: "auto-check",
    checkKey: "pageStructure",
    link: "https://validator.w3.org/",
    desc: "Headings hierarchy aur semantic HTML.",
  },
  {
    id: 18,
    cat: "Technical",
    task: "Redirect Chain",
    method: "auto-check",
    checkKey: "redirectChain",
    link: "https://httpstatus.io/",
    desc: "Redirect chain aur hops check.",
  },
  {
    id: 19,
    cat: "Branding",
    task: "Favicon Check",
    method: "auto-check",
    checkKey: "favicon",
    link: "https://realfavicongenerator.net/",
    desc: "Favicon aur Apple touch icon check.",
  },
  {
    id: 20,
    cat: "i18n",
    task: "Language & hreflang",
    method: "auto-check",
    checkKey: "language",
    link: "https://technicalseo.com/tools/hreflang/",
    desc: "HTML lang attribute aur hreflang tags.",
  },
  {
    id: 21,
    cat: "Performance",
    task: "DOM Size Check",
    method: "auto-check",
    checkKey: "domSize",
    link: "https://pagespeed.web.dev/",
    desc: "Total HTML elements aur DOM depth.",
  },
  {
    id: 22,
    cat: "Performance",
    task: "Inline CSS/JS Check",
    method: "auto-check",
    checkKey: "jsOptimization",
    link: "https://pagespeed.web.dev/",
    desc: "Async/defer, render-blocking, inline CSS/JS.",
  },
  {
    id: 23,
    cat: "Social",
    task: "Social Media Links",
    method: "auto-check",
    checkKey: "socialLinks",
    link: "https://metatags.io/",
    desc: "Facebook, Twitter, Instagram, etc. links.",
  },
  {
    id: 24,
    cat: "Analytics",
    task: "Analytics Detection",
    method: "auto-check",
    checkKey: "analyticsDetection",
    link: "https://builtwith.com/",
    desc: "Google Analytics, GTM, etc. detection.",
  },
  {
    id: 25,
    cat: "Code Quality",
    task: "Deprecated HTML",
    method: "auto-check",
    checkKey: "deprecatedHtml",
    link: "https://validator.w3.org/",
    desc: "Purane HTML tags aur attributes check.",
  },
  {
    id: 26,
    cat: "Performance",
    task: "Compression Check",
    method: "auto-check",
    checkKey: "compression",
    link: "https://www.giftofspeed.com/gzip-test/",
    desc: "Gzip/Brotli compression enabled check.",
  },
  {
    id: 27,
    cat: "Security",
    task: "HTTP Headers",
    method: "auto-check",
    checkKey: "httpHeaders",
    link: "https://securityheaders.com/",
    desc: "Cache-Control, ETag, server exposure.",
  },
  {
    id: 28,
    cat: "UX",
    task: "Custom 404 Page",
    method: "auto-check",
    checkKey: "custom404",
    link: "https://httpstatus.io/",
    desc: "Custom 404 error page check.",
  },
  {
    id: 29,
    cat: "Images",
    task: "Image Formats",
    method: "auto-check",
    checkKey: "imageFormats",
    link: "https://squoosh.app/",
    desc: "WebP/AVIF modern formats use check.",
  },
  {
    id: 30,
    cat: "Mobile",
    task: "Tap Targets",
    method: "auto-check",
    checkKey: "tapTargets",
    link: "https://search.google.com/test/mobile-friendly",
    desc: "Clickable elements spacing aur size.",
  },
  {
    id: 31,
    cat: "On-Page",
    task: "Duplicate H1",
    method: "auto-check",
    checkKey: "duplicateH1",
    link: "https://validator.w3.org/",
    desc: "Ek se zyada H1 tags check.",
  },
  {
    id: 32,
    cat: "On-Page",
    task: "Title/Desc Length",
    method: "auto-check",
    checkKey: "titleDescLength",
    link: "https://metatags.io/",
    desc: "Title 60 chars, Desc 160 chars limit.",
  },
  {
    id: 33,
    cat: "Technical",
    task: "Indexability Check",
    method: "auto-check",
    checkKey: "indexability",
    link: "https://www.google.com/webmasters/tools/",
    desc: "Noindex, X-Robots-Tag, canonical mismatch.",
  },
  {
    id: 34,
    cat: "Performance",
    task: "CLS Risk Factors",
    method: "auto-check",
    checkKey: "clsRisk",
    link: "https://pagespeed.web.dev/",
    desc: "Images without dimensions, late CSS loading.",
  },
  {
    id: 35,
    cat: "Performance",
    task: "Lazy Loading",
    method: "auto-check",
    checkKey: "lazyLoading",
    link: "https://pagespeed.web.dev/",
    desc: "Image/iframe lazy loading aur fetchpriority.",
  },
  {
    id: 36,
    cat: "Content",
    task: "Content Freshness",
    method: "auto-check",
    checkKey: "contentFreshness",
    link: "https://search.google.com/search-console",
    desc: "Last-Modified, datePublished/dateModified.",
  },
  {
    id: 37,
    cat: "Authority",
    task: "E-E-A-T Signals",
    method: "auto-check",
    checkKey: "eeatSignals",
    link: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content",
    desc: "Author, About, Contact, Privacy page links.",
  },
  {
    id: 38,
    cat: "Accessibility",
    task: "Accessibility Basics",
    method: "auto-check",
    checkKey: "accessibilityBasics",
    link: "https://wave.webaim.org/",
    desc: "ARIA roles, form labels, focus outline, lang.",
  },
  {
    id: 39,
    cat: "On-Page",
    task: "URL Structure",
    method: "auto-check",
    checkKey: "urlStructure",
    link: "https://developers.google.com/search/docs/crawling-indexing/url-structure",
    desc: "Clean URL, length, parameters, depth.",
  },
  {
    id: 40,
    cat: "On-Page",
    task: "Breadcrumb Schema",
    method: "auto-check",
    checkKey: "breadcrumbSchema",
    link: "https://developers.google.com/search/docs/appearance/structured-data/breadcrumb",
    desc: "BreadcrumbList JSON-LD aur HTML breadcrumbs.",
  },
  {
    id: 41,
    cat: "Legal",
    task: "Cookie Consent",
    method: "auto-check",
    checkKey: "cookieConsent",
    link: "https://www.cookiebot.com/",
    desc: "GDPR cookie consent banner detection.",
  },
  {
    id: 42,
    cat: "Technical",
    task: "Entity Schema Depth",
    method: "auto-check",
    checkKey: "entitySchema",
    link: "https://validator.schema.org/",
    desc: "Organization, FAQ, HowTo, Article schema types.",
  },
  {
    id: 43,
    cat: "Technical",
    task: "Broken Links",
    method: "auto-check",
    checkKey: "brokenLinks",
    link: "https://www.deadlinkchecker.com/",
    desc: "Page ke saare links check karke 404s dhoondhein.",
  },
];
