export const checkMeta = {
  "Content Analysis": {
    impact: "High",
    fix: "Add: Write 300+ words of unique, keyword-rich content.",
    why: "Thin pages rarely rank — Google needs substance to evaluate.",
    effort: "Medium",
  },
  "Readability Score": {
    impact: "Medium",
    fix: "Simplify: Shorten sentences and use everyday vocabulary.",
    why: "Complex text increases bounce rate, hurting dwell time signals.",
    effort: "Low",
  },
  "Keyword Density": {
    impact: "High",
    fix: "Optimize: Include primary keyword 2-3 times naturally.",
    why: "Without keyword signals, Google can't match intent to your page.",
    effort: "Low",
  },
  "Meta Tags Check": {
    impact: "High",
    fix: "Write: Add title (<60 chars) and description (<160 chars).",
    why: "Title/desc are the #1 factor in click-through from search results.",
    effort: "Low",
  },
  "Link Profile": {
    impact: "Medium",
    fix: "Build: Add internal links to related pages + outbound links.",
    why: "Internal links spread authority; outbound links show topical relevance.",
    effort: "Medium",
  },
  "Outbound Links": {
    impact: "Low",
    fix: "Link: Reference authoritative external sources.",
    why: "Citing trusted sources builds E-E-A-T trust signals.",
    effort: "Low",
  },
  "Security Headers": {
    impact: "Medium",
    fix: "Configure: Add CSP, X-Frame-Options, HSTS via server config.",
    why: "Missing headers = vulnerable site; Google may flag as unsafe.",
    effort: "High",
  },
  "Sitemap Generator": {
    impact: "High",
    fix: "Create: Generate sitemap.xml and submit to Search Console.",
    why: "Without sitemap, crawlers may miss important pages.",
    effort: "Low",
  },
  "Robots.txt Gen": {
    impact: "High",
    fix: "Create: Add robots.txt with proper allow/disallow rules.",
    why: "Missing robots.txt lets bots crawl everything including junk URLs.",
    effort: "Low",
  },
  "Website Speed": {
    impact: "High",
    fix: "Optimize: Minify CSS/JS, compress images, enable caching.",
    why: "Speed is a direct ranking factor; slow sites lose 40% of visitors.",
    effort: "High",
  },
  "Image Compression": {
    impact: "Medium",
    fix: "Add: Write descriptive alt text for every image.",
    why: "Alt text helps Google Images ranking and accessibility compliance.",
    effort: "Low",
  },
  "Open Graph Tags": {
    impact: "Medium",
    fix: "Add: Include og:title, og:description, og:image tags.",
    why: "Social shares drive traffic; bad previews kill click-through.",
    effort: "Low",
  },
  "SSL Certificate": {
    impact: "High",
    fix: "Renew: Update SSL certificate before expiry.",
    why: "HTTPS is a confirmed ranking signal; expired certs show warnings.",
    effort: "Low",
  },
  "Structured Data": {
    impact: "High",
    fix: "Implement: Add JSON-LD schema (Organization, Article, etc.).",
    why: "Rich snippets from schema boost CTR by up to 30%.",
    effort: "Medium",
  },
  "Mobile-Friendly": {
    impact: "High",
    fix: "Fix: Add viewport meta tag and responsive CSS.",
    why: "Mobile-first indexing means non-mobile sites won't rank.",
    effort: "Medium",
  },
  "Canonical URL": {
    impact: "High",
    fix: "Add: Set self-referencing canonical tag.",
    why: "Duplicate content dilutes ranking power across multiple URLs.",
    effort: "Low",
  },
  "Page Structure": {
    impact: "Medium",
    fix: "Refactor: Use semantic HTML — header, nav, main, footer.",
    why: "Semantic HTML helps crawlers understand page hierarchy.",
    effort: "Medium",
  },
  "Redirect Chain": {
    impact: "Medium",
    fix: "Fix: Point all redirects directly to the final URL.",
    why: "Each redirect hop loses ~10% of link equity and adds latency.",
    effort: "Medium",
  },
  "Favicon Check": {
    impact: "Low",
    fix: "Add: Upload favicon.ico and apple-touch-icon.",
    why: "Favicons improve brand recognition in tabs and bookmarks.",
    effort: "Low",
  },
  "Language & hreflang": {
    impact: "Low",
    fix: "Set: Add lang attribute on the html element.",
    why: "Helps search engines serve the right language to users.",
    effort: "Low",
  },
  "DOM Size Check": {
    impact: "Medium",
    fix: "Reduce: Keep DOM under 1500 elements for speed.",
    why: "Large DOM increases memory usage and slows rendering.",
    effort: "High",
  },
  "Inline CSS/JS Check": {
    impact: "Medium",
    fix: "Extract: Move inline scripts to external files with defer.",
    why: "Inline code blocks rendering; external files can be cached.",
    effort: "Medium",
  },
  "Social Media Links": {
    impact: "Low",
    fix: "Add: Include links to active social profiles.",
    why: "Social profiles build brand presence and trust signals.",
    effort: "Low",
  },
  "Analytics Detection": {
    impact: "Medium",
    fix: "Install: Add Google Analytics or equivalent tracking.",
    why: "Without analytics, you can't measure what to improve.",
    effort: "Low",
  },
  "Deprecated HTML": {
    impact: "Low",
    fix: "Replace: Swap deprecated tags (font, center) with CSS.",
    why: "Deprecated HTML signals outdated code to crawlers.",
    effort: "Low",
  },
  Compression: {
    impact: "Medium",
    fix: "Enable: Turn on gzip/brotli compression on server.",
    why: "Compression cuts page size 60-80%, directly improving load time.",
    effort: "Low",
  },
  "HTTP Headers": {
    impact: "Medium",
    fix: "Set: Configure Cache-Control and ETag headers.",
    why: "Proper caching headers reduce repeat-visit load times.",
    effort: "Low",
  },
  "Custom 404 Page": {
    impact: "Low",
    fix: "Create: Build a custom 404 page with navigation.",
    why: "Good 404s retain users instead of losing them to dead ends.",
    effort: "Low",
  },
  "Image Formats": {
    impact: "Medium",
    fix: "Convert: Switch images to WebP/AVIF format.",
    why: "Modern formats are 25-50% smaller than JPEG/PNG.",
    effort: "Medium",
  },
  "Tap Targets": {
    impact: "Medium",
    fix: "Resize: Make all buttons/links at least 48×48px.",
    why: "Small tap targets cause mobile usability failures in GSC.",
    effort: "Low",
  },
  "Duplicate H1": {
    impact: "High",
    fix: "Fix: Use exactly one H1 per page with primary keyword.",
    why: "Multiple H1s confuse crawler hierarchy and dilute topical focus.",
    effort: "Low",
  },
  "Title/Desc Length": {
    impact: "High",
    fix: "Adjust: Keep title 30-60 chars, description 120-160.",
    why: "Truncated or empty SERP snippets hurt click-through rates.",
    effort: "Low",
  },
  "Indexability Check": {
    impact: "High",
    fix: "Remove: Delete noindex tag and fix canonical mismatches.",
    why: "Noindex = invisible to Google. Page won't rank at all.",
    effort: "Low",
  },
  "CLS Risk Factors": {
    impact: "High",
    fix: "Fix: Add width/height to all images, avoid late-loaded CSS.",
    why: "CLS is a Core Web Vital — poor scores trigger ranking demotion.",
    effort: "Medium",
  },
  "Lazy Loading": {
    impact: "Medium",
    fix: "Add: Set loading='lazy' on below-fold images/iframes.",
    why: "Lazy loading improves initial page load speed significantly.",
    effort: "Low",
  },
  "Content Freshness": {
    impact: "Medium",
    fix: "Add: Include datePublished/dateModified in schema.",
    why: "Fresh content signals relevance; stale dates drop rankings.",
    effort: "Low",
  },
  "E-E-A-T Signals": {
    impact: "High",
    fix: "Create: Add About, Contact, Privacy pages + author info.",
    why: "Google's Quality Raters explicitly check for E-E-A-T signals.",
    effort: "Medium",
  },
  "Accessibility Basics": {
    impact: "Medium",
    fix: "Add: Include ARIA roles, form labels, focus outlines.",
    why: "Accessibility issues affect 15%+ of users and may trigger penalties.",
    effort: "Medium",
  },
  "URL Structure": {
    impact: "Medium",
    fix: "Clean: Use short, lowercase, hyphenated URLs.",
    why: "Clean URLs improve crawlability and user trust in SERPs.",
    effort: "Medium",
  },
  "Breadcrumb Schema": {
    impact: "Medium",
    fix: "Add: Implement BreadcrumbList JSON-LD markup.",
    why: "Breadcrumb rich snippets improve SERP appearance and CTR.",
    effort: "Low",
  },
  "Cookie Consent": {
    impact: "Low",
    fix: "Add: Implement GDPR-compliant cookie consent banner.",
    why: "Missing consent = legal risk in EU/UK markets.",
    effort: "Low",
  },
  "Entity Schema Depth": {
    impact: "High",
    fix: "Add: Implement Organization, Article, FAQ schema.",
    why: "Rich entity data unlocks Knowledge Panel and FAQ rich results.",
    effort: "Medium",
  },
  "Broken Links": {
    impact: "High",
    fix: "Fix: Repair or remove all broken (404) links on the page.",
    why: "Broken links waste crawl budget and hurt user experience.",
    effort: "Medium",
  },
};
